#!/usr/bin/env node
/**
 * gcode2krl v3.2 — OrcaSlicer GCode → KUKA KRL converter
 *
 * Output format follows KUKA WorkVisual FOLD convention:
 *   - DECL E6POS t[10] pre-read buffer for ADVANCE=3 safety
 *   - PNT_LIN DEFFCT returns E6POS, LIN executed externally
 *   - FOLD/ENDFOLD wrapping for all blocks
 *
 * Usage:
 *   OrcaSlicer mode:   gcode2krl.exe <gcode_file>                    (in-place)
 *   Standalone mode:   gcode2krl.exe <input.gcode> <output.src>      (input→output)
 *   With options:      gcode2krl.exe <input> <output> [--name=JOBNAME] [--start-config=config.json]
 *
 * Changelog v3.2:
 *   - Incremental streaming output (avoids OOM on large files)
 *   - Global crash handler with stack trace logging
 *   - File size validation and progress reporting
 *   - Memory usage monitoring
 */

"use strict";

const fs = require('fs');
const path = require('path');

// ──────────────────────────────────────────
// Crash resilience
// ──────────────────────────────────────────
let logStream = null;
function setupLog(outputPath) {
  const logDir = path.dirname(outputPath);
  const logPath = path.join(logDir, 'gcode2krl_debug.log');
  try { logStream = fs.createWriteStream(logPath, { flags: 'a' }); } catch (_) {}
}
function log(msg) {
  const ts = new Date().toISOString();
  const line = `[${ts}] ${msg}`;
  console.error(line);
  if (logStream) { try { logStream.write(line + '\n'); } catch (_) {} }
}

process.on('uncaughtException', (err) => {
  try {
    const msg = `CRASH (uncaughtException): ${err.message}\n${err.stack || '(no stack)'}`;
    console.error(msg);
    if (logStream) { logStream.write(`[FATAL] ${msg}\n`); logStream.end(); }
  } catch (_) {}
  process.exit(1);
});
process.on('unhandledRejection', (reason) => {
  try {
    const msg = `CRASH (unhandledRejection): ${reason}`;
    console.error(msg);
    if (logStream) { logStream.write(`[FATAL] ${msg}\n`); logStream.end(); }
  } catch (_) {}
  process.exit(1);
});

// ──────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────
function setVal(v, pre) {
  if (v === undefined || v === null) return pre !== undefined ? pre.toString() : '0';
  return v.toString();
}

function fmt1(v, def) { return (v !== undefined && v !== null ? v : (def !== undefined ? def : 0)).toFixed(1); }
function fmt2(v, def) { return (v !== undefined && v !== null ? v : (def !== undefined ? def : 0)).toFixed(2); }
function fmt3(v, def) { return (v !== undefined && v !== null ? v : (def !== undefined ? def : 0)).toFixed(3); }

/**
 * Parse a GCode line into { cmd, params: { X, Y, Z, E, F, S, ... } }
 */
function parseGCode(line) {
  line = line.split(';')[0].trim();
  if (!line) return null;

  const parts = line.split(/\s+/);
  const cmd = parts[0].toUpperCase();
  const params = {};

  for (let i = 1; i < parts.length; i++) {
    const key = parts[i][0].toUpperCase();
    const val = parseFloat(parts[i].slice(1));
    if (!isNaN(val)) params[key] = val;
  }
  return { cmd, params };
}

function fmtMem() {
  const m = process.memoryUsage();
  return `${Math.round(m.heapUsed / 1024 / 1024)}MB / ${Math.round(m.heapTotal / 1024 / 1024)}MB`;
}

// ──────────────────────────────────────────
// START POSITION config
// ──────────────────────────────────────────
let startConfig = null;
const DEFAULT_START = {
  axis: { A1: 5, A2: -85.75, A3: 109.02, A4: 0.30, A5: 64.18, A6: 2.93, E1: 0, E2: 0, E3: 0, E4: 0 },
  cart: { X: 0, Y: 0, Z: 200, A: 112, B: 20.03, C: -177.85, E1: 0, E2: 0, E3: 0, E4: 0 },
  speed: 0.25,
  cdis: 100,
  advance: 3,
  heat: { T1: 220, T2: 220, T3: 230, T4: 220, T5: 0, T6: 0 },
  heatMinTemp: 180
};

function loadStartConfig(cfgPath) {
  try {
    const raw = fs.readFileSync(cfgPath, 'utf-8');
    const cfg = JSON.parse(raw);
    startConfig = { ...DEFAULT_START, ...cfg };
    if (cfg.axis) startConfig.axis = { ...DEFAULT_START.axis, ...cfg.axis };
    if (cfg.cart) startConfig.cart = { ...DEFAULT_START.cart, ...cfg.cart };
    if (cfg.heat)  startConfig.heat  = { ...DEFAULT_START.heat,  ...cfg.heat };
    log(`Loaded start config from ${cfgPath}`);
  } catch (e) {
    log(`Warning: could not load start config (${cfgPath}), using defaults. ${e.message}`);
    startConfig = { ...DEFAULT_START };
  }
}
function sc() { return startConfig || DEFAULT_START; }

// ──────────────────────────────────────────
// Header
// ──────────────────────────────────────────
function emitHeader(inputName) {
  return [
    '&ACCESS RVP',
    '&REL 3',
    `&COMMENT Generated by gcode2krl v3.2 from ${inputName}`,
    '&PARAM EDITMASK = *',
    '&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe',
  ];
}

function emitBanner() {
  return [
    '  ;═══════════════════════════════════════════════════════════',
    '  ;Aura3D Printing Path Generated by OrcaSlicer with gcode2krl',
    '  ;═══════════════════════════════════════════════════════════',
  ];
}

// ──────────────────────────────────────────
// FOLD Init motion
// ──────────────────────────────────────────
function foldInitMotion(cfg) {
  const ax = cfg.axis;
  const ct = cfg.cart;
  return [
    '   ;FOLD Init motion',
    '      DECL E6POS t[10]',
    '      GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )',
    '      INTERRUPT ON 3',
    '      BAS (#INITMOV,0 )',
    '      $BWDSTART = FALSE',
    '      PDAT_ACT = {VEL 20,ACC 100,APO_DIST 50}',
    '      FDAT_ACT = {TOOL_NO 1,BASE_NO 1,IPO_FRAME #BASE}',
    '      BAS (#PTP_PARAMS,20)',
    '      ;ready postion',
    `      PTP {A1 ${fmt1(ax.A1)},A2 ${fmt1(ax.A2)},A3 ${fmt1(ax.A3)},A4 ${fmt1(ax.A4)},A5 ${fmt1(ax.A5)},A6 ${fmt1(ax.A6)},E1 ${fmt1(ax.E1)},E2 ${fmt1(ax.E2)},E3 ${fmt1(ax.E3)},E4 ${fmt1(ax.E4)}}`,
    '      ;Run to print postion',
    `      $VEL.CP=${cfg.speed}`,
    `      $APO.CDIS=${cfg.cdis}`,
    `      $ADVANCE=${cfg.advance}`,
    `      LIN {X ${fmt1(ct.X)}, Y ${fmt1(ct.Y)}, Z ${fmt1(ct.Z)}, A ${fmt2(ct.A)}, B ${fmt2(ct.B)}, C ${fmt2(ct.C)}, E1 ${fmt1(ct.E1)}, E2 ${fmt1(ct.E2)}, E3 ${fmt1(ct.E3)}, E4 ${fmt1(ct.E4)}}`,
    '   ;ENDFOLD',
    '',
  ];
}

// ──────────────────────────────────────────
// FOLD Init PLC
// ──────────────────────────────────────────
function foldInitPLC(cfg) {
  const h = cfg.heat;
  const lines = ['   ;FOLD Init PLC'];

  const temps = [h.T1, h.T2, h.T3, h.T4, h.T5, h.T6];
  for (let i = 0; i < temps.length; i++) {
    if (temps[i] > 0) {
      lines.push(`      PNT_HEAT_ON(${i + 1}, ${Math.round(temps[i])})`);
    }
  }

  lines.push(`      PNT_HEAT_WAIT_ALL(${cfg.heatMinTemp || 180})`);
  lines.push('      HALT ;pause the program until press start key for safty');
  lines.push('   ;ENDFOLD (INI)');
  lines.push('');
  return lines;
}

// ──────────────────────────────────────────
// FOLD Finish (Shutdown)
// ──────────────────────────────────────────
function foldFinish() {
  return [
    '   ;FOLD Finish',
    '      PNT_RETRACT()',
    '      PNT_FAN_OFF()',
    '      PNT_HEAT_ALL(0, 0, 0, 0, 0, 0)',
    '      PNT_FINISH()',
    '   ;ENDFOLD',
  ];
}

// ──────────────────────────────────────────
// E-value state tracker
// ──────────────────────────────────────────
class EState {
  constructor() { this.absolute = 0; this.relative = false; }
  setRelative(v) { this.relative = (v === 1); }
  reset()       { this.absolute = 0; }
  applyE(e) {
    if (e === undefined || e === null) return this.absolute;
    if (this.relative) this.absolute += e;
    else this.absolute = e;
    return this.absolute;
  }
}

// ──────────────────────────────────────────
// Stream writer helper (avoids buffering entire output in memory)
// ──────────────────────────────────────────
class StreamWriter {
  constructor(filepath) {
    this.filepath = filepath;
    this.count = 0;
    this.buffer = [];
    this.bufferSize = 0;
    this.flushThreshold = 500 * 1024; // flush every 500KB
    const dir = path.dirname(filepath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    this.fd = fs.openSync(filepath, 'w');
  }

  writeLine(str) {
    this.buffer.push(str);
    this.bufferSize += str.length + 2; // +2 for \r\n
    this.count++;

    if (this.bufferSize >= this.flushThreshold) {
      this._flush();
    }
  }

  writeLines(arr) {
    for (const s of arr) this.writeLine(s);
  }

  _flush() {
    if (this.buffer.length === 0) return;
    const chunk = this.buffer.join('\r\n') + '\r\n';
    fs.writeSync(this.fd, chunk);
    this.buffer.length = 0;
    this.bufferSize = 0;
  }

  close() {
    if (this.buffer.length > 0) {
      const chunk = this.buffer.join('\r\n') + '\r\n';
      fs.writeSync(this.fd, chunk);
      this.buffer.length = 0;
    }
    fs.closeSync(this.fd);
  }
}

// ──────────────────────────────────────────
// Main GCode→KRL converter (streaming output)
// ──────────────────────────────────────────
function convert(inputPath, outputPath, jobName, progressCb) {
  log(`Reading input: ${inputPath} (${fmtMem()})`);

  // Check file size
  let stat;
  try { stat = fs.statSync(inputPath); } catch (e) { throw new Error(`Cannot stat input: ${e.message}`); }
  const sizeMB = Math.round(stat.size / 1024 / 1024);
  log(`Input size: ${sizeMB} MB`);

  if (stat.size > 500 * 1024 * 1024) {
    log(`WARNING: File is ${sizeMB} MB — may run out of memory`);
  }

  // Read with explicit encoding check
  let input;
  try {
    input = fs.readFileSync(inputPath, 'utf-8');
  } catch (e) {
    throw new Error(`Cannot read input file: ${e.message}`);
  }

  if (!input || input.length === 0) {
    throw new Error('Input file is empty');
  }

  log(`File read complete (${fmtMem()})`);

  const lines = input.split(/\r?\n/);
  const cfg = sc();
  const out = new StreamWriter(outputPath);
  const eState = new EState();
  const fname = jobName || path.basename(outputPath, path.extname(outputPath)).replace(/[^a-zA-Z0-9_]/g, '_');

  log(`Starting conversion: ${lines.length} input lines → ${outputPath}`);

  // ── Header ──
  out.writeLines(emitHeader(path.basename(inputPath)));
  out.writeLine(`DEF ${fname}()`);
  out.writeLines(emitBanner());
  out.writeLine('');

  // ── FOLD Init motion ──
  out.writeLines(foldInitMotion(cfg));

  // ── FOLD Init PLC ──
  out.writeLines(foldInitPLC(cfg));

  // ── FOLD Print Path ──
  out.writeLine('   ;FOLD Print Path');
  out.writeLine('');

  // Parse print info from GCode comments (info only)
  let printTime = '', printWeight = '', printSize = '';
  let filamentType = '', nozzleDiam = '', layerHeight = '';
  for (const raw of lines) {
    const t = raw.trim();
    if (t.startsWith('; estimated printing time')) printTime = t.split(':').slice(1).join(':').trim();
    if (t.startsWith('; total filament weight'))  printWeight = t.split(':').slice(1).join(':').trim();
    if (t.startsWith('; filament_type ='))       filamentType = t.split('=')[1]?.trim() || '';
    if (t.startsWith('; nozzle_diameter ='))     nozzleDiam = t.split('=')[1]?.trim() || '';
    if (t.startsWith('; layer_height ='))        layerHeight = t.split('=')[1]?.trim() || '';
    if (t.startsWith('; model_bounding_box'))    printSize = t.split(':').slice(1).join(':').trim();
  }
  if (printTime)   out.writeLine(`      ;PrintTime = ${printTime}`);
  if (printWeight) out.writeLine(`      ;PrintWeight = ${printWeight}`);
  if (printSize)   out.writeLine(`      ;PrintSize = (X,Y,Z) = (${printSize})`);
  if (filamentType) out.writeLine(`      ;Material = ${filamentType}`);
  if (nozzleDiam)   out.writeLine(`      ;Nozzle = ${nozzleDiam}mm`);
  if (layerHeight)  out.writeLine(`      ;LayerH = ${layerHeight}mm`);

  // ── State machine for layer/wiping/retraction ──
  let tIdx         = 0;        // t[n] index, 1-10 cycling
  let layerCount   = 0;
  let totalLayers  = 0;
  let prevZ        = null;
  let fanOn        = false;
  let inLayerFold  = false;
  let retracting   = false;
  let g92Emitted   = false;

  // Count total layers
  for (const raw of lines) {
    if (raw.match(/^;(LAYER_CHANGE|BEFORE_LAYER_CHANGE|AFTER_LAYER_CHANGE|Z:)/i)) totalLayers++;
  }

  function nextT() {
    if (tIdx === 10) {
      out.writeLine('         ;back to t[1] aviod advance');
    }
    tIdx = (tIdx % 10) + 1;
    return tIdx;
  }

  function closeLayerFold() {
    if (inLayerFold) {
      out.writeLine('      ;ENDFOLD');
      out.writeLine('');
      inLayerFold = false;
    }
  }

  function openLayerFold(num, pct) {
    out.writeLine(`      ;FOLD Layer ${num}`);
    if (pct !== undefined) out.writeLine(`         ;Progress = ${pct}`);
    inLayerFold = true;
  }

  // Orientation constants for PNT_LIN
  const oriA = fmt2(cfg.cart.A);
  const oriB = fmt2(cfg.cart.B);
  const oriC = fmt2(cfg.cart.C);

  let lineNum = 0;
  let lastProgressLog = 0;

  for (const raw of lines) {
    lineNum++;

    // Progress logging every 500K lines
    if (progressCb && lineNum - lastProgressLog >= 500000) {
      progressCb(lineNum, lines.length);
      lastProgressLog = lineNum;
    }

    // Pass through layer-related comments only
    if (raw.startsWith(';')) {
      if (raw.match(/^;(LAYER_CHANGE|BEFORE_LAYER_CHANGE|AFTER_LAYER_CHANGE|Z:|HEIGHT:|TYPE:|WIPE_START|WIPE_END)/)) {
        // handle below
      } else {
        continue;
      }
    }

    // ── Layer change detection ──
    const isLayerBoundary = raw.match(/^;(LAYER_CHANGE|BEFORE_LAYER_CHANGE|AFTER_LAYER_CHANGE)/i);
    const isZmarker = raw.match(/^;Z:/i);

    if (isZmarker) {
      const zVal = parseFloat(raw.split(':')[1]?.trim());
      if (!isNaN(zVal)) {
        if (prevZ !== null && zVal > prevZ + 0.001) layerCount++;
        prevZ = zVal;
      }
      continue;
    }

    if (isLayerBoundary) {
      closeLayerFold();
      layerCount++;
      const pct = totalLayers > 0 ? Math.round((layerCount / totalLayers) * 100) : 0;
      openLayerFold(layerCount, pct);
      out.writeLine('         PNT_G92_E0()');
      g92Emitted = true;
      continue;
    }

    // ── Wipe markers ──
    if (raw.match(/^;WIPE_START/i)) { out.writeLine('         ; WIPE_START'); continue; }
    if (raw.match(/^;WIPE_END/i))   { out.writeLine('         ; WIPE_END');   continue; }

    const parsed = parseGCode(raw);
    if (!parsed) continue;

    const { cmd, params } = parsed;

    // ── M82/M83: E-axis mode ──
    if (cmd === 'M82') { eState.setRelative(0); continue; }
    if (cmd === 'M83') { eState.setRelative(1); continue; }

    // ── G92 E0 ──
    if (cmd === 'G92' && params.E !== undefined && params.E === 0) {
      if (g92Emitted) { g92Emitted = false; continue; }
      eState.reset();
      out.writeLine('         PNT_G92_E0()');
      continue;
    }

    // ── Fan control ──
    if (cmd === 'M106') {
      const s = (params.S !== undefined) ? params.S : 255;
      if (s === 0) {
        if (fanOn) out.writeLine('         PNT_FAN_OFF()');
        fanOn = false;
      } else {
        const pct = Math.round(s / 255 * 100);
        out.writeLine(`         PNT_FAN_SET(${pct})`);
        fanOn = true;
      }
      continue;
    }
    if (cmd === 'M107') {
      if (fanOn) out.writeLine('         PNT_FAN_OFF()');
      fanOn = false;
      continue;
    }

    // ── G0: Travel move ──
    if (cmd === 'G0') {
      const x = params.X, y = params.Y, z = params.Z;
      const vel = params.F ? Math.round(params.F / 60) : 300;
      out.writeLine(`         PNT_G0(${setVal(x, 0)}, ${setVal(y, 0)}, ${setVal(z, prevZ || 0)}, ${oriA}, ${oriB}, ${oriC}, ${vel})`);
      continue;
    }

    // ── G1: Print/extrusion move ──
    if (cmd === 'G1') {
      const x = params.X, y = params.Y, z = params.Z;
      const e = eState.applyE(params.E);
      const vel = params.F ? Math.round(params.F / 60) : 50;
      const idx = nextT();

      out.writeLine(`         t[${idx}]= PNT_LIN(${fmt3(x, 0)}, ${fmt3(y, 0)}, ${fmt3(z, prevZ || 0)}, ${oriA}, ${oriB}, ${oriC}, ${fmt3(e)}, ${fmt1(vel)})`);
      out.writeLine(`         LIN t[${idx}] C_DIS`);
      continue;
    }
  }

  // Close any open layer fold
  closeLayerFold();

  // ── Close Print Path FOLD ──
  out.writeLine('   ;ENDFOLD');
  out.writeLine('');

  // ── FOLD Finish ──
  out.writeLines(foldFinish());

  // ── END ──
  out.writeLine('');
  out.writeLine('END');

  const lineCount = out.count;
  out.close();

  log(`Conversion complete: ${lines.length} input lines → ${lineCount} output lines (${fmtMem()})`);
  return lineCount;
}

// ──────────────────────────────────────────
// CLI entry
// ──────────────────────────────────────────
function main() {
  const args = process.argv.slice(2);

  let inputPath, outputPath, jobName = '';

  // Parse args for --start-config and --name
  const cleanArgs = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith('--start-config=')) {
      loadStartConfig(args[i].split('=')[1]);
    } else if (args[i].startsWith('--name=')) {
      jobName = args[i].split('=')[1];
    } else {
      cleanArgs.push(args[i]);
    }
  }

  if (cleanArgs.length < 1) {
    console.error('Usage:');
    console.error('  OrcaSlicer mode:  gcode2krl <gcode_file>                                  (in-place)');
    console.error('  Standalone mode:  gcode2krl <input.gcode> <output.src> [--name=JOB]       (input→output)');
    console.error('  With config:      gcode2krl <input> <output> --start-config=config.json');
    console.error('');
    console.error('Config JSON fields:');
    console.error('  axis.{A1..A6,E1..E4}    Joint angles for PTP ready position');
    console.error('  cart.{X,Y,Z,A,B,C,E1..E4}  Approach position and tool orientation');
    console.error('  speed                   Approach speed (m/s, default 0.25)');
    console.error('  cdis                    Approximation distance (mm, default 100)');
    console.error('  advance                 Look-ahead buffer (default 3)');
    console.error('  heat.{T1..T6}           Target temperatures per zone');
    console.error('  heatMinTemp             Minimum temp to wait for all zones (default 180)');
    process.exit(1);
  }

  inputPath = cleanArgs[0];

  if (cleanArgs.length >= 2) {
    outputPath = cleanArgs[1];
  } else {
    outputPath = inputPath;
  }

  // Setup logging
  setupLog(outputPath);

  log(`gcode2krl v3.2 starting`);
  log(`Args: ${cleanArgs.join(' ')}`);

  if (!fs.existsSync(inputPath)) {
    log(`ERROR: File not found: ${inputPath}`);
    console.error(`ERROR: File not found: ${inputPath}`);
    process.exit(1);
  }

  if (!jobName) {
    jobName = path.basename(outputPath, path.extname(outputPath)).replace(/[^a-zA-Z0-9_]/g, '_');
    if (!jobName || /^\d/.test(jobName)) jobName = 'P_' + jobName;
  }

  log(`Converting ${path.basename(inputPath)} → ${path.basename(outputPath)} [${jobName}]`);
  console.error(`gcode2krl v3.2: Converting ${path.basename(inputPath)}...`);

  try {
    const lineCount = convert(inputPath, outputPath, jobName, (n, total) => {
      const pct = total > 0 ? Math.round(n / total * 100) : 0;
      console.error(`  Progress: ${pct}% (${n}/${total} lines, ${fmtMem()})`);
    });
    console.error(`Generated: ${path.basename(outputPath)} (${lineCount} lines)`);
    console.error(`gcode2krl: Done! Rename to .SRC before loading to KUKA controller.`);
    log(`Success: ${lineCount} lines written`);
    process.exit(0);
  } catch (e) {
    log(`FATAL: ${e.message}`);
    log(`Stack: ${e.stack || '(no stack)'}`);
    console.error(`ERROR: Conversion failed: ${e.message}`);
    if (e.stack) console.error(e.stack);
    process.exit(1);
  }
}

main();
