namespace GCode2Krl.Cli;

// ──────────────────────────────────────────
// KRL format emitter
//   Generates all fixed-format KRL blocks:
//   header, banner, init motion, init PLC,
//   finish, sub-program headers, main program.
// ──────────────────────────────────────────

/// <summary>Generates KRL source code blocks matching the JS version output exactly</summary>
public static class KrlEmitter
{
    /// <summary>Emit the KUKA file header (&amp;ACCESS, &amp;REL, &amp;COMMENT, &amp;PARAM)</summary>
    public static string[] EmitHeader(string inputName)
    {
        return new[]
        {
            "&ACCESS RVP",
            "&REL 3",
            $"&COMMENT Generated by gcode2krl v3.2 from {inputName}",
            "&PARAM EDITMASK = *",
            "&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe",
        };
    }

    /// <summary>Emit the Aura3D banner comment block</summary>
    public static string[] EmitBanner()
    {
        return new[]
        {
            "  ;═══════════════════════════════════════════════════════════",
            "  ;Aura3D Printing Path Generated by OrcaSlicer with gcode2krl",
            "  ;═══════════════════════════════════════════════════════════",
        };
    }

    /// <summary>
    /// Emit the Init Motion FOLD block:
    ///   DECL E6POS t[10], INTERRUPT, BAS (#INITMOV), PTP ready, LIN approach
    /// </summary>
    public static string[] EmitInitMotion(StartConfig cfg)
    {
        var ax = cfg.Axis;
        var ct = cfg.Cart;
        return new[]
        {
            "   ;FOLD Init motion",
            "      DECL E6POS t[10]",
            "      GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )",
            "      INTERRUPT ON 3",
            "      BAS (#INITMOV,0 )",
            "      $BWDSTART = FALSE",
            "      PDAT_ACT = {VEL 20,ACC 100,APO_DIST 50}",
            "      FDAT_ACT = {TOOL_NO 1,BASE_NO 1,IPO_FRAME #BASE}",
            "      BAS (#PTP_PARAMS,20)",
            "      ;ready postion",
            $"      PTP {{A1 {FormatHelper.Fmt1(ax.A1)},A2 {FormatHelper.Fmt1(ax.A2)},A3 {FormatHelper.Fmt1(ax.A3)},A4 {FormatHelper.Fmt1(ax.A4)},A5 {FormatHelper.Fmt1(ax.A5)},A6 {FormatHelper.Fmt1(ax.A6)},E1 {FormatHelper.Fmt1(ax.E1)},E2 {FormatHelper.Fmt1(ax.E2)},E3 {FormatHelper.Fmt1(ax.E3)},E4 {FormatHelper.Fmt1(ax.E4)}}}",
            "      ;Run to print postion",
            $"      $VEL.CP={cfg.Speed}",
            $"      $APO.CDIS={cfg.Cdis}",
            $"      $ADVANCE={cfg.Advance}",
            $"      LIN {{X {FormatHelper.Fmt1(ct.X)}, Y {FormatHelper.Fmt1(ct.Y)}, Z {FormatHelper.Fmt1(ct.Z)}, A {FormatHelper.Fmt2(ct.A)}, B {FormatHelper.Fmt2(ct.B)}, C {FormatHelper.Fmt2(ct.C)}, E1 {FormatHelper.Fmt1(ct.E1)}, E2 {FormatHelper.Fmt1(ct.E2)}, E3 {FormatHelper.Fmt1(ct.E3)}, E4 {FormatHelper.Fmt1(ct.E4)}}}",
            "   ;ENDFOLD",
            "",
        };
    }

    /// <summary>
    /// Emit the Init PLC FOLD block:
    ///   PNT_HEAT_ON for each zone, PNT_HEAT_WAIT_ALL, HALT
    /// </summary>
    public static string[] EmitInitPlc(StartConfig cfg)
    {
        var lines = new List<string> { "   ;FOLD Init PLC" };

        var temps = new[] { cfg.Heat.T1, cfg.Heat.T2, cfg.Heat.T3, cfg.Heat.T4, cfg.Heat.T5, cfg.Heat.T6 };
        for (var i = 0; i < temps.Length; i++)
        {
            if (temps[i] > 0)
                lines.Add($"      PNT_HEAT_ON({i + 1}, {Math.Round(temps[i])})");
        }

        lines.Add($"      PNT_HEAT_WAIT_ALL({cfg.HeatMinTemp})");
        lines.Add("      HALT ;pause the program until press start key for safty");
        lines.Add("   ;ENDFOLD (INI)");
        lines.Add("");
        return lines.ToArray();
    }

    /// <summary>
    /// Emit the Finish FOLD block:
    ///   PNT_RETRACT, PNT_FAN_OFF, PNT_HEAT_ALL(0), PNT_FINISH
    /// </summary>
    public static string[] EmitFinish()
    {
        return new[]
        {
            "   ;FOLD Finish",
            "      PNT_RETRACT()",
            "      PNT_FAN_OFF()",
            "      PNT_HEAT_ALL(0, 0, 0, 0, 0, 0)",
            "      PNT_FINISH()",
            "   ;ENDFOLD",
        };
    }

    /// <summary>
    /// Emit the header and DEF block for a sub-program file
    /// (used in split mode)
    /// </summary>
    public static void EmitSubProgramHeader(KrlStreamWriter writer, string inputName, string subName,
        string jobName, int chunkNum, int firstLayer, int lastLayer, long totalBytes, bool isPreambleOnly)
    {
        writer.WriteLines(EmitHeader(inputName));
        writer.WriteLine($"DEF {subName}()");
        writer.WriteLine("");
        writer.WriteLine("  ;═══════════════════════════════════════════════════════════");
        writer.WriteLine($"  ;{jobName} Sub-program #{chunkNum}");

        var mb = (totalBytes / 1024.0 / 1024.0).ToString("F1", System.Globalization.CultureInfo.InvariantCulture);
        if (!isPreambleOnly)
            writer.WriteLine($"  ;Layers {firstLayer}–{lastLayer}, ~{mb} MB");
        else
            writer.WriteLine($"  ;Preamble only, ~{mb} MB");

        writer.WriteLine("  ;═══════════════════════════════════════════════════════════");
        writer.WriteLine("");
        writer.WriteLine("  DECL E6POS t[10]");
        writer.WriteLine("");
    }

    /// <summary>
    /// Emit the main program file — includes EXT declarations, INI fold,
    /// STARTPOSITION fold, LIN SPEED fold, Init PLC, Print Path with sub-program calls,
    /// and Finish fold.
    /// </summary>
    public static void EmitMainProgram(KrlStreamWriter writer, string inputName, string jobName,
        string[] subNames, ChunkInfo[] chunks, StartConfig cfg, int targetChunkMb)
    {
        // Header
        writer.WriteLines(EmitHeader(inputName));
        writer.WriteLine($"DEF {jobName}()");
        writer.WriteLine("");

        // EXT declarations
        foreach (var sn in subNames)
            writer.WriteLine($"EXT {sn}()");
        writer.WriteLine("");

        // Banner
        writer.WriteLines(EmitBanner());
        writer.WriteLine("");

        // FOLD INI
        writer.WriteLine("  ;FOLD INI");
        writer.WriteLine("    ;FOLD BASISTECH INI");
        writer.WriteLine("      GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM ( )");
        writer.WriteLine("      INTERRUPT ON 3");
        writer.WriteLine("      BAS (#INITMOV,0 )");
        writer.WriteLine("    ;ENDFOLD (BASISTECH INI)");
        writer.WriteLine("  ;ENDFOLD (INI)");
        writer.WriteLine("");

        // FOLD STARTPOSITION
        var ax = cfg.Axis;
        var ct = cfg.Cart;
        var posComment = string.Join(",",
            $"A1 {FormatHelper.Fmt1(ax.A1)}",
            $"A2 {FormatHelper.Fmt1(ax.A2)}",
            $"A3 {FormatHelper.Fmt1(ax.A3)}",
            $"A4 {FormatHelper.Fmt1(ax.A4)}",
            $"A5 {FormatHelper.Fmt1(ax.A5)}",
            $"A6 {FormatHelper.Fmt1(ax.A6)}",
            $"E1 {FormatHelper.Fmt1(ax.E1)}",
            "E2 0", "E3 0", "E4 0");

        writer.WriteLine($"  ;FOLD STARTPOSITION - BASE IS 1, TOOL IS 1, SPEED IS 20%, POSITION IS {posComment}");
        writer.WriteLine("    $BWDSTART = FALSE");
        writer.WriteLine("    PDAT_ACT = {VEL 20,ACC 100,APO_DIST 50}");
        writer.WriteLine("    FDAT_ACT = {TOOL_NO 1,BASE_NO 1,IPO_FRAME #BASE}");
        writer.WriteLine("    BAS (#PTP_PARAMS,20)");
        writer.WriteLine($"    PTP {{A1 {FormatHelper.Fmt1(ax.A1)},A2 {FormatHelper.Fmt1(ax.A2)},A3 {FormatHelper.Fmt1(ax.A3)},A4 {FormatHelper.Fmt1(ax.A4)},A5 {FormatHelper.Fmt1(ax.A5)},A6 {FormatHelper.Fmt1(ax.A6)},E1 {FormatHelper.Fmt1(ax.E1)},E2 {FormatHelper.Fmt1(ax.E2)},E3 {FormatHelper.Fmt1(ax.E3)},E4 {FormatHelper.Fmt1(ax.E4)}}}");
        writer.WriteLine("  ;ENDFOLD");
        writer.WriteLine("");

        // FOLD LIN SPEED
        writer.WriteLine($"  ;FOLD LIN SPEED IS {cfg.Speed} m/sec, INTERPOLATION SETTINGS IN FOLD");
        writer.WriteLine($"    $VEL.CP={cfg.Speed}");
        writer.WriteLine($"    $APO.CDIS={cfg.Cdis}");
        writer.WriteLine($"    $ADVANCE={cfg.Advance}");
        writer.WriteLine("  ;ENDFOLD");
        writer.WriteLine("");

        // Init PLC
        writer.WriteLines(EmitInitPlc(cfg));

        // FOLD Print Path
        writer.WriteLine("  ;FOLD Print Path");
        writer.WriteLine("");
        writer.WriteLine($"    ;Chunks: {chunks.Length} sub-program(s), target chunk size ~{targetChunkMb} MB");
        for (var i = 0; i < chunks.Length; i++)
        {
            var c = chunks[i];
            var mb = (c.TotalBytes / 1024.0 / 1024.0).ToString("F1", System.Globalization.CultureInfo.InvariantCulture);
            writer.WriteLine($"    ;  {subNames[i]}: layers {c.FirstLayerIndex}–{c.LastLayerIndex}, ~{mb} MB");
        }
        writer.WriteLine("");
        foreach (var sn in subNames)
            writer.WriteLine($"    {sn}()");
        writer.WriteLine("");
        writer.WriteLine("  ;ENDFOLD");
        writer.WriteLine("");

        // Finish
        writer.WriteLines(EmitFinish());

        // END
        writer.WriteLine("");
        writer.WriteLine("END");
    }
}
